config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  get 'static_pages/about'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  get '/admin', to: redirect('/auth/facebook')

  get '/record/:id', to: 'graffitis#show', as: 'graffiti_show'
  get '/list', to: 'graffitis#index', as: 'graffiti_index'

  scope '/admin' do
    resources :graffitis, except: [:index, :show] do
      resources :photos
    end
  end
end

app/models/graffiti.rb
class Graffiti < ActiveRecord::Base
  has_many :photos

  validates :surname, presence: true, length: { minimum: 2 }
  validates :location, presence: true

  validates :graffiti_month, presence: true, if: "graffiti_dayinmonth.present?"

# TODO: would like validation to force month if day in month has been specified
#  with_options if: validates :graffiti_dayinmonth, presence: true,
#             if: [ validates :graffiti_month, presence: true ]
#  end

#:month_present?

  def month_present?
    graffiti_month != ""
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :graffiti
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :graffiti

  # TODO: would like to validate but don't know how to redirect the user back
  # to the parent form as the form is only submitted with photo details
  #validates :link, format: { with: /\Ahttps?:\/\//,
  #  message: "must start http:// or https://" }
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  helper_method :current_user

  private

    # Confirm user is logged in
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to '/auth/facebook'
      end
    end

    # Confirm user is an administrator
    def admin_user
      unless logged_in_user
        unless current_user.admin?
          flash[:danger] = "You are not authorised."
          redirect_to '/'
        end
      end
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/graffitis_controller.rb
class GraffitisController < ApplicationController
  before_action :admin_user, only: [:new,:edit,:create,:update,:destroy]

  def index
    @graffitis = Graffiti.where(deleted: 0)
    @graffitis = @graffitis.order(:location, surname: :asc)
  end

  def show
    @graffiti = Graffiti.find(params[:id])
  end

  def new
    @graffiti = Graffiti.new
  end

  def edit
    @graffiti = Graffiti.find(params[:id])
  end

  def create
#    render plain: params[:graffiti].inspect

    @graffiti = Graffiti.new(graffiti_params)
    if @graffiti.save
      redirect_to graffiti_show_path(@graffiti)
    else
      render 'new'
    end
  end

  def update
    @graffiti = Graffiti.find(params[:id])
    if @graffiti.update(graffiti_params)
      redirect_to graffiti_show_path(@graffiti)
    else
      render 'edit'
    end
  end

  def destroy
    @graffiti = Graffiti.find(params[:id])
    @graffiti.deleted = 1
    @graffiti.save

    redirect_to '/list'
  end

  private
    def graffiti_params
      params.require(:graffiti).permit(:surname,
                                       :forenames,
                                       :rank,
                                       :soldier_number,
                                       :location,
                                       :graffiti_year,
                                       :graffiti_month,
                                       :graffiti_dayinmonth,
                                       :dob,
                                       :survived_war,
                                       :notes,
                                       :deleted)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  require 'flickraw'

  before_action :set_photo, only: [:show, :destroy]
  before_action :set_flickr, only: [:create, :destroy]

  def new
  end

  def create
    @graffiti = Graffiti.find(params[:graffiti_id])
#    @photo = @graffiti.photos.create(photo_params)
#    redirect_to edit_graffiti_path(@graffiti)

    photo_id = flickr.upload_photo params[:photo].tempfile.path, :title => "My Title", :description => "My Description"
    photo_url = FlickRaw.url_o(flickr.photos.getInfo(photo_id: photo_id))

    #@photo = Photo.new(photo_id: photo_id, photo_url: photo_url)
    @photo = @graffiti.photos.create(flickr_id: photo_id, link: photo_url)

#    respond_to do |format|
      if @photo.save
        redirect_to edit_graffiti_path(@graffiti)
#        format.html { redirect_to @edit_graffiti_path, notice: ‘Photo was successfully created.’ }
#        format.json { render action: ‘show’, status: :created, location: @photo }
#      else
#        format.html { render action: ‘new’ }
#        format.json { render json: @graffiti.photo.errors, status: :unprocessable_entity }
      end
#    end


  end

  def update
    @graffiti = Graffiti.find(params[:graffiti_id])
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
      redirect_to graffiti_show_path(@graffiti)
    else
      render 'edit'
    end
  end

  def destroy
    @graffiti = Graffiti.find(params[:graffiti_id])
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to edit_graffiti_path(@graffiti)
  end
 
  private
    def photo_params
      params.require(:photo).permit(:photo, :link, :caption, :flickr_id)
    end

    def set_photo
      @graffiti = Graffiti.find(params[:graffiti_id])
      @photo = Photo.find(params[:id])
    end

    def set_flickr
      FlickRaw.api_key = ENV['FLICKR_API_KEY']
      FlickRaw.shared_secret = ENV['FLICKR_API_SECRET']

      flickr.access_token = ENV['FLICKR_ACCESS_TOKEN']
      flickr.access_secret = ENV['FLICKR_ACCESS_SECRET']
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_back_or root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

  private

    # Confirm the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # not used, untested
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graffitis_helper.rb
module GraffitisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Return true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # Redirect to stored location (or to the default)
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Store the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/graffitis/edit.html.erb
  <div class="row">
    <div class="large-12 columns">
      <h1>Edit record</h1>
    </div>
  </div>

<%= render 'form' %>

<% @graffiti.photos.each do |photo| %>
  <%= form_for([@graffiti, photo]) do |g| %>
  <div class="row">
    <div class="large-4 medium-4 columns">
      <%= g.label :link %>
      <%= g.text_field :link, size: 35 %>
    </div>
    <div class="large-8 medium-8 columns">
      <%= g.submit('Update', class: 'tiny radius button') %>
      <%= link_to 'Delete', [photo.graffiti, photo],
                   method: :delete,
                   data: { confirm: 'Are you sure?' },
                   class: 'tiny radius button' %>
    </div>
  </div>
  <% end %>
<% end %>


  <%= form_for([@graffiti, @graffiti.photos.build], html: {:multipart => true}) do |h| %>

<% if @graffiti.errors.any? %>
<div id=”error_explanation”>
<h2><%= pluralize(@graffiti.errors.count, “error”) %> prohibited this photo from being saved:</h2>

<ul>
<% @graffiti.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<%= file_field_tag :photo %>
<%= h.submit('Add', clas: 'tiny radius button') %>

<!--
  <div class="row">
    <div class="large-4 medium-4 columns">
      <%= h.label :link %>
      <%= h.text_field :link, size: 35 %>
    </div>
    <div class="large-8 medium-8 columns">
      <%= h.submit('Add', class: 'tiny radius button') %>
    </div>
  </div>
-->
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <%= link_to 'Back to index', graffiti_index_path, class: 'small radius button' %>
    </div>
  </div>

app/views/graffitis/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>List of all graffiti</h1>
  </div>
</div>

<div class="row">
    <div class="large-3 medium-3 small-3 columns">
      <strong>Name</strong>
    </div>
    <div class="large-3 medium-3 small-3 columns">
      <strong>Location</strong>
    </div>
    <div class="large-6 medium-6 small-6 columns">
      <strong>Actions</strong>
    </div>
  </div>
  <% @graffitis.each do |graffiti| %>
  <div class="row">
    <div class="large-3 medium-3 small-3 columns">
      <%= graffiti.surname %>, <%= graffiti.forenames %>
    </div>
    <div class="large-3 medium-3 small-3 columns">
      <%= graffiti.location %>
    </div>
    <div class="large-6 medium-6 small-6 columns">
      <%= link_to 'See full record', graffiti_show_path(graffiti), class: 'small radius button' %>
      <% if current_user %>
        <% if current_user.admin? %>
        <%= link_to 'Edit', edit_graffiti_path(graffiti), class: 'small radius button' %></td>
        <%= link_to 'Delete', [graffiti],
                     method: :delete,
                     class: 'small radius button',
                     data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
  </div>
 <% end %>

<%if current_user %>
  <%if current_user.admin? %>
<div class="row">
  <div class="large-12 columns">
    <%= link_to 'Add a record', new_graffiti_path, class: 'small radius button' %>
  </div>
</div>
  <% end %>
<% end %>

app/views/graffitis/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Record new graffiti</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="large-12 columns">
    <%= link_to 'Back to index', graffiti_index_path, class: 'small radius button' %>
  </div>
</div>

app/views/graffitis/show.html.erb
<!-- <%= months = [ '', 'January', 'February', 'March', 'April', 'May', 'June','July','August','September','October','November','December' ] %> -->

  <div class="row">
    <div class="large-12 columns">
      <ul class="large-block-grid-2">
        <li><% @graffiti.photos.each do |photo| %>
          <img src="<%= photo.link %>">
          <% end %></li>
        <li>
          <strong>Name:</strong>
          <%= @graffiti.surname %>, <%= @graffiti.forenames %>
        <br />
          <strong>Rank:</strong>
          <%= @graffiti.rank %>
        <br />
          <strong>Number:</strong>
          <%= @graffiti.soldier_number %>
        <br />
          <strong>DOB:</strong>
          <%= @graffiti.dob.to_formatted_s(:long) if @graffiti.dob.present? %>
        <br />
          <strong>Location:</strong>
          <%= @graffiti.location %>
        <br />
          <strong>Date of graffiti:</strong>
          <%= @graffiti.graffiti_dayinmonth
          # array lookup fails if month is blank
          if ( @graffiti.graffiti_month.present? )
          then
            months.fetch(@graffiti.graffiti_month, "")
          end
          @graffiti.graffiti_year %>
        <br />
          <strong>Survived war:</strong>
          <%= @graffiti.survived_war %>
        <br />
          <strong>Notes:</strong>
          <%= @graffiti.notes %>
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
    <strong>Want more info?</strong> Do you have anything you can add? Email <a href="mailto:Matt.leonard@durandgroup.org.uk">thesecretary@durandgroup.org.uk</a>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <%= link_to 'Back to index', graffiti_index_path, class: 'small radius button' %>
    </div>
  </div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>World War 1 Graffiti</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <% if current_user %>
    Signed in as <strong><%= current_user.name %>
    <%if current_user.admin? %>
    (admin)
     <% end %>
    </strong>
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>About us</h1>
<p>We are a charity that excavates WW1 trenches and posts information about what we find. We have been estabilshed for many years and even have a book out!</p>

app/views/static_pages/home.html.erb
<div style="text-align:center">
<h1>First World War Graffiti</h1>
<p>Welcome to our web site!</p>
<p>Here you will find information on WW1 soldiers.</p>
<p>
<ul>
<li><a href="/list">View our list of soldier graffiti</a></li>
<li><a href="/about">About us</a></li>
</ul>
</p>
<p>Brought to you by <a href="http://www.durandgroup.org.uk">The Durand Group</a></p>
</div>